// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/sglang.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fsglang_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fsglang_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fsglang_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fsglang_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fsglang_2eproto;
namespace sglang {
class GenerateReq;
struct GenerateReqDefaultTypeInternal;
extern GenerateReqDefaultTypeInternal _GenerateReq_default_instance_;
class GenerateResp;
struct GenerateRespDefaultTypeInternal;
extern GenerateRespDefaultTypeInternal _GenerateResp_default_instance_;
class GenerateResp_MetaInfoEntry_DoNotUse;
struct GenerateResp_MetaInfoEntry_DoNotUseDefaultTypeInternal;
extern GenerateResp_MetaInfoEntry_DoNotUseDefaultTypeInternal _GenerateResp_MetaInfoEntry_DoNotUse_default_instance_;
class SamplingParams;
struct SamplingParamsDefaultTypeInternal;
extern SamplingParamsDefaultTypeInternal _SamplingParams_default_instance_;
}  // namespace sglang
PROTOBUF_NAMESPACE_OPEN
template<> ::sglang::GenerateReq* Arena::CreateMaybeMessage<::sglang::GenerateReq>(Arena*);
template<> ::sglang::GenerateResp* Arena::CreateMaybeMessage<::sglang::GenerateResp>(Arena*);
template<> ::sglang::GenerateResp_MetaInfoEntry_DoNotUse* Arena::CreateMaybeMessage<::sglang::GenerateResp_MetaInfoEntry_DoNotUse>(Arena*);
template<> ::sglang::SamplingParams* Arena::CreateMaybeMessage<::sglang::SamplingParams>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sglang {

// ===================================================================

class SamplingParams final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sglang.SamplingParams) */ {
 public:
  inline SamplingParams() : SamplingParams(nullptr) {}
  ~SamplingParams() override;
  explicit PROTOBUF_CONSTEXPR SamplingParams(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SamplingParams(const SamplingParams& from);
  SamplingParams(SamplingParams&& from) noexcept
    : SamplingParams() {
    *this = ::std::move(from);
  }

  inline SamplingParams& operator=(const SamplingParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline SamplingParams& operator=(SamplingParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SamplingParams& default_instance() {
    return *internal_default_instance();
  }
  static inline const SamplingParams* internal_default_instance() {
    return reinterpret_cast<const SamplingParams*>(
               &_SamplingParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SamplingParams& a, SamplingParams& b) {
    a.Swap(&b);
  }
  inline void Swap(SamplingParams* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SamplingParams* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SamplingParams* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SamplingParams>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SamplingParams& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SamplingParams& from) {
    SamplingParams::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SamplingParams* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sglang.SamplingParams";
  }
  protected:
  explicit SamplingParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMaxNewTokensFieldNumber = 1,
    kStopTokenIdFieldNumber = 2,
    kIgnoreEosFieldNumber = 3,
    kTemperatureFieldNumber = 4,
    kTopPFieldNumber = 5,
    kTopKFieldNumber = 6,
    kFrequencyPenaltyFieldNumber = 7,
  };
  // int32 max_new_tokens = 1;
  void clear_max_new_tokens();
  int32_t max_new_tokens() const;
  void set_max_new_tokens(int32_t value);
  private:
  int32_t _internal_max_new_tokens() const;
  void _internal_set_max_new_tokens(int32_t value);
  public:

  // int32 stop_token_id = 2;
  void clear_stop_token_id();
  int32_t stop_token_id() const;
  void set_stop_token_id(int32_t value);
  private:
  int32_t _internal_stop_token_id() const;
  void _internal_set_stop_token_id(int32_t value);
  public:

  // bool ignore_eos = 3;
  void clear_ignore_eos();
  bool ignore_eos() const;
  void set_ignore_eos(bool value);
  private:
  bool _internal_ignore_eos() const;
  void _internal_set_ignore_eos(bool value);
  public:

  // float temperature = 4;
  void clear_temperature();
  float temperature() const;
  void set_temperature(float value);
  private:
  float _internal_temperature() const;
  void _internal_set_temperature(float value);
  public:

  // float top_p = 5;
  void clear_top_p();
  float top_p() const;
  void set_top_p(float value);
  private:
  float _internal_top_p() const;
  void _internal_set_top_p(float value);
  public:

  // int32 top_k = 6;
  void clear_top_k();
  int32_t top_k() const;
  void set_top_k(int32_t value);
  private:
  int32_t _internal_top_k() const;
  void _internal_set_top_k(int32_t value);
  public:

  // float frequency_penalty = 7;
  void clear_frequency_penalty();
  float frequency_penalty() const;
  void set_frequency_penalty(float value);
  private:
  float _internal_frequency_penalty() const;
  void _internal_set_frequency_penalty(float value);
  public:

  // @@protoc_insertion_point(class_scope:sglang.SamplingParams)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t max_new_tokens_;
    int32_t stop_token_id_;
    bool ignore_eos_;
    float temperature_;
    float top_p_;
    int32_t top_k_;
    float frequency_penalty_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fsglang_2eproto;
};
// -------------------------------------------------------------------

class GenerateReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sglang.GenerateReq) */ {
 public:
  inline GenerateReq() : GenerateReq(nullptr) {}
  ~GenerateReq() override;
  explicit PROTOBUF_CONSTEXPR GenerateReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GenerateReq(const GenerateReq& from);
  GenerateReq(GenerateReq&& from) noexcept
    : GenerateReq() {
    *this = ::std::move(from);
  }

  inline GenerateReq& operator=(const GenerateReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenerateReq& operator=(GenerateReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenerateReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenerateReq* internal_default_instance() {
    return reinterpret_cast<const GenerateReq*>(
               &_GenerateReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GenerateReq& a, GenerateReq& b) {
    a.Swap(&b);
  }
  inline void Swap(GenerateReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenerateReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenerateReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GenerateReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GenerateReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GenerateReq& from) {
    GenerateReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenerateReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sglang.GenerateReq";
  }
  protected:
  explicit GenerateReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputIdsFieldNumber = 2,
    kTextFieldNumber = 1,
    kSamplingParamsFieldNumber = 3,
    kReqIdFieldNumber = 4,
  };
  // repeated int32 input_ids = 2;
  int input_ids_size() const;
  private:
  int _internal_input_ids_size() const;
  public:
  void clear_input_ids();
  private:
  int32_t _internal_input_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_input_ids() const;
  void _internal_add_input_ids(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_input_ids();
  public:
  int32_t input_ids(int index) const;
  void set_input_ids(int index, int32_t value);
  void add_input_ids(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      input_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_input_ids();

  // string text = 1;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // .sglang.SamplingParams sampling_params = 3;
  bool has_sampling_params() const;
  private:
  bool _internal_has_sampling_params() const;
  public:
  void clear_sampling_params();
  const ::sglang::SamplingParams& sampling_params() const;
  PROTOBUF_NODISCARD ::sglang::SamplingParams* release_sampling_params();
  ::sglang::SamplingParams* mutable_sampling_params();
  void set_allocated_sampling_params(::sglang::SamplingParams* sampling_params);
  private:
  const ::sglang::SamplingParams& _internal_sampling_params() const;
  ::sglang::SamplingParams* _internal_mutable_sampling_params();
  public:
  void unsafe_arena_set_allocated_sampling_params(
      ::sglang::SamplingParams* sampling_params);
  ::sglang::SamplingParams* unsafe_arena_release_sampling_params();

  // uint64 req_id = 4;
  void clear_req_id();
  uint64_t req_id() const;
  void set_req_id(uint64_t value);
  private:
  uint64_t _internal_req_id() const;
  void _internal_set_req_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:sglang.GenerateReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > input_ids_;
    mutable std::atomic<int> _input_ids_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    ::sglang::SamplingParams* sampling_params_;
    uint64_t req_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fsglang_2eproto;
};
// -------------------------------------------------------------------

class GenerateResp_MetaInfoEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GenerateResp_MetaInfoEntry_DoNotUse, 
    std::string, float,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GenerateResp_MetaInfoEntry_DoNotUse, 
    std::string, float,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> SuperType;
  GenerateResp_MetaInfoEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR GenerateResp_MetaInfoEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit GenerateResp_MetaInfoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const GenerateResp_MetaInfoEntry_DoNotUse& other);
  static const GenerateResp_MetaInfoEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const GenerateResp_MetaInfoEntry_DoNotUse*>(&_GenerateResp_MetaInfoEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "sglang.GenerateResp.MetaInfoEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fsglang_2eproto;
};

// -------------------------------------------------------------------

class GenerateResp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sglang.GenerateResp) */ {
 public:
  inline GenerateResp() : GenerateResp(nullptr) {}
  ~GenerateResp() override;
  explicit PROTOBUF_CONSTEXPR GenerateResp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GenerateResp(const GenerateResp& from);
  GenerateResp(GenerateResp&& from) noexcept
    : GenerateResp() {
    *this = ::std::move(from);
  }

  inline GenerateResp& operator=(const GenerateResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenerateResp& operator=(GenerateResp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenerateResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenerateResp* internal_default_instance() {
    return reinterpret_cast<const GenerateResp*>(
               &_GenerateResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GenerateResp& a, GenerateResp& b) {
    a.Swap(&b);
  }
  inline void Swap(GenerateResp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenerateResp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenerateResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GenerateResp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GenerateResp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GenerateResp& from) {
    GenerateResp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenerateResp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sglang.GenerateResp";
  }
  protected:
  explicit GenerateResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kOutputIdsFieldNumber = 2,
    kMetaInfoFieldNumber = 3,
    kTextFieldNumber = 1,
    kFinishedFieldNumber = 4,
  };
  // repeated int32 output_ids = 2;
  int output_ids_size() const;
  private:
  int _internal_output_ids_size() const;
  public:
  void clear_output_ids();
  private:
  int32_t _internal_output_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_output_ids() const;
  void _internal_add_output_ids(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_output_ids();
  public:
  int32_t output_ids(int index) const;
  void set_output_ids(int index, int32_t value);
  void add_output_ids(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      output_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_output_ids();

  // map<string, float> meta_info = 3;
  int meta_info_size() const;
  private:
  int _internal_meta_info_size() const;
  public:
  void clear_meta_info();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
      _internal_meta_info() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
      _internal_mutable_meta_info();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
      meta_info() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
      mutable_meta_info();

  // string text = 1;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // bool finished = 4;
  void clear_finished();
  bool finished() const;
  void set_finished(bool value);
  private:
  bool _internal_finished() const;
  void _internal_set_finished(bool value);
  public:

  // @@protoc_insertion_point(class_scope:sglang.GenerateResp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > output_ids_;
    mutable std::atomic<int> _output_ids_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        GenerateResp_MetaInfoEntry_DoNotUse,
        std::string, float,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> meta_info_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    bool finished_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fsglang_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SamplingParams

// int32 max_new_tokens = 1;
inline void SamplingParams::clear_max_new_tokens() {
  _impl_.max_new_tokens_ = 0;
}
inline int32_t SamplingParams::_internal_max_new_tokens() const {
  return _impl_.max_new_tokens_;
}
inline int32_t SamplingParams::max_new_tokens() const {
  // @@protoc_insertion_point(field_get:sglang.SamplingParams.max_new_tokens)
  return _internal_max_new_tokens();
}
inline void SamplingParams::_internal_set_max_new_tokens(int32_t value) {
  
  _impl_.max_new_tokens_ = value;
}
inline void SamplingParams::set_max_new_tokens(int32_t value) {
  _internal_set_max_new_tokens(value);
  // @@protoc_insertion_point(field_set:sglang.SamplingParams.max_new_tokens)
}

// int32 stop_token_id = 2;
inline void SamplingParams::clear_stop_token_id() {
  _impl_.stop_token_id_ = 0;
}
inline int32_t SamplingParams::_internal_stop_token_id() const {
  return _impl_.stop_token_id_;
}
inline int32_t SamplingParams::stop_token_id() const {
  // @@protoc_insertion_point(field_get:sglang.SamplingParams.stop_token_id)
  return _internal_stop_token_id();
}
inline void SamplingParams::_internal_set_stop_token_id(int32_t value) {
  
  _impl_.stop_token_id_ = value;
}
inline void SamplingParams::set_stop_token_id(int32_t value) {
  _internal_set_stop_token_id(value);
  // @@protoc_insertion_point(field_set:sglang.SamplingParams.stop_token_id)
}

// bool ignore_eos = 3;
inline void SamplingParams::clear_ignore_eos() {
  _impl_.ignore_eos_ = false;
}
inline bool SamplingParams::_internal_ignore_eos() const {
  return _impl_.ignore_eos_;
}
inline bool SamplingParams::ignore_eos() const {
  // @@protoc_insertion_point(field_get:sglang.SamplingParams.ignore_eos)
  return _internal_ignore_eos();
}
inline void SamplingParams::_internal_set_ignore_eos(bool value) {
  
  _impl_.ignore_eos_ = value;
}
inline void SamplingParams::set_ignore_eos(bool value) {
  _internal_set_ignore_eos(value);
  // @@protoc_insertion_point(field_set:sglang.SamplingParams.ignore_eos)
}

// float temperature = 4;
inline void SamplingParams::clear_temperature() {
  _impl_.temperature_ = 0;
}
inline float SamplingParams::_internal_temperature() const {
  return _impl_.temperature_;
}
inline float SamplingParams::temperature() const {
  // @@protoc_insertion_point(field_get:sglang.SamplingParams.temperature)
  return _internal_temperature();
}
inline void SamplingParams::_internal_set_temperature(float value) {
  
  _impl_.temperature_ = value;
}
inline void SamplingParams::set_temperature(float value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:sglang.SamplingParams.temperature)
}

// float top_p = 5;
inline void SamplingParams::clear_top_p() {
  _impl_.top_p_ = 0;
}
inline float SamplingParams::_internal_top_p() const {
  return _impl_.top_p_;
}
inline float SamplingParams::top_p() const {
  // @@protoc_insertion_point(field_get:sglang.SamplingParams.top_p)
  return _internal_top_p();
}
inline void SamplingParams::_internal_set_top_p(float value) {
  
  _impl_.top_p_ = value;
}
inline void SamplingParams::set_top_p(float value) {
  _internal_set_top_p(value);
  // @@protoc_insertion_point(field_set:sglang.SamplingParams.top_p)
}

// int32 top_k = 6;
inline void SamplingParams::clear_top_k() {
  _impl_.top_k_ = 0;
}
inline int32_t SamplingParams::_internal_top_k() const {
  return _impl_.top_k_;
}
inline int32_t SamplingParams::top_k() const {
  // @@protoc_insertion_point(field_get:sglang.SamplingParams.top_k)
  return _internal_top_k();
}
inline void SamplingParams::_internal_set_top_k(int32_t value) {
  
  _impl_.top_k_ = value;
}
inline void SamplingParams::set_top_k(int32_t value) {
  _internal_set_top_k(value);
  // @@protoc_insertion_point(field_set:sglang.SamplingParams.top_k)
}

// float frequency_penalty = 7;
inline void SamplingParams::clear_frequency_penalty() {
  _impl_.frequency_penalty_ = 0;
}
inline float SamplingParams::_internal_frequency_penalty() const {
  return _impl_.frequency_penalty_;
}
inline float SamplingParams::frequency_penalty() const {
  // @@protoc_insertion_point(field_get:sglang.SamplingParams.frequency_penalty)
  return _internal_frequency_penalty();
}
inline void SamplingParams::_internal_set_frequency_penalty(float value) {
  
  _impl_.frequency_penalty_ = value;
}
inline void SamplingParams::set_frequency_penalty(float value) {
  _internal_set_frequency_penalty(value);
  // @@protoc_insertion_point(field_set:sglang.SamplingParams.frequency_penalty)
}

// -------------------------------------------------------------------

// GenerateReq

// string text = 1;
inline void GenerateReq::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& GenerateReq::text() const {
  // @@protoc_insertion_point(field_get:sglang.GenerateReq.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GenerateReq::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sglang.GenerateReq.text)
}
inline std::string* GenerateReq::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:sglang.GenerateReq.text)
  return _s;
}
inline const std::string& GenerateReq::_internal_text() const {
  return _impl_.text_.Get();
}
inline void GenerateReq::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* GenerateReq::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* GenerateReq::release_text() {
  // @@protoc_insertion_point(field_release:sglang.GenerateReq.text)
  return _impl_.text_.Release();
}
inline void GenerateReq::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sglang.GenerateReq.text)
}

// repeated int32 input_ids = 2;
inline int GenerateReq::_internal_input_ids_size() const {
  return _impl_.input_ids_.size();
}
inline int GenerateReq::input_ids_size() const {
  return _internal_input_ids_size();
}
inline void GenerateReq::clear_input_ids() {
  _impl_.input_ids_.Clear();
}
inline int32_t GenerateReq::_internal_input_ids(int index) const {
  return _impl_.input_ids_.Get(index);
}
inline int32_t GenerateReq::input_ids(int index) const {
  // @@protoc_insertion_point(field_get:sglang.GenerateReq.input_ids)
  return _internal_input_ids(index);
}
inline void GenerateReq::set_input_ids(int index, int32_t value) {
  _impl_.input_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:sglang.GenerateReq.input_ids)
}
inline void GenerateReq::_internal_add_input_ids(int32_t value) {
  _impl_.input_ids_.Add(value);
}
inline void GenerateReq::add_input_ids(int32_t value) {
  _internal_add_input_ids(value);
  // @@protoc_insertion_point(field_add:sglang.GenerateReq.input_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GenerateReq::_internal_input_ids() const {
  return _impl_.input_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GenerateReq::input_ids() const {
  // @@protoc_insertion_point(field_list:sglang.GenerateReq.input_ids)
  return _internal_input_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GenerateReq::_internal_mutable_input_ids() {
  return &_impl_.input_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GenerateReq::mutable_input_ids() {
  // @@protoc_insertion_point(field_mutable_list:sglang.GenerateReq.input_ids)
  return _internal_mutable_input_ids();
}

// .sglang.SamplingParams sampling_params = 3;
inline bool GenerateReq::_internal_has_sampling_params() const {
  return this != internal_default_instance() && _impl_.sampling_params_ != nullptr;
}
inline bool GenerateReq::has_sampling_params() const {
  return _internal_has_sampling_params();
}
inline void GenerateReq::clear_sampling_params() {
  if (GetArenaForAllocation() == nullptr && _impl_.sampling_params_ != nullptr) {
    delete _impl_.sampling_params_;
  }
  _impl_.sampling_params_ = nullptr;
}
inline const ::sglang::SamplingParams& GenerateReq::_internal_sampling_params() const {
  const ::sglang::SamplingParams* p = _impl_.sampling_params_;
  return p != nullptr ? *p : reinterpret_cast<const ::sglang::SamplingParams&>(
      ::sglang::_SamplingParams_default_instance_);
}
inline const ::sglang::SamplingParams& GenerateReq::sampling_params() const {
  // @@protoc_insertion_point(field_get:sglang.GenerateReq.sampling_params)
  return _internal_sampling_params();
}
inline void GenerateReq::unsafe_arena_set_allocated_sampling_params(
    ::sglang::SamplingParams* sampling_params) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.sampling_params_);
  }
  _impl_.sampling_params_ = sampling_params;
  if (sampling_params) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sglang.GenerateReq.sampling_params)
}
inline ::sglang::SamplingParams* GenerateReq::release_sampling_params() {
  
  ::sglang::SamplingParams* temp = _impl_.sampling_params_;
  _impl_.sampling_params_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::sglang::SamplingParams* GenerateReq::unsafe_arena_release_sampling_params() {
  // @@protoc_insertion_point(field_release:sglang.GenerateReq.sampling_params)
  
  ::sglang::SamplingParams* temp = _impl_.sampling_params_;
  _impl_.sampling_params_ = nullptr;
  return temp;
}
inline ::sglang::SamplingParams* GenerateReq::_internal_mutable_sampling_params() {
  
  if (_impl_.sampling_params_ == nullptr) {
    auto* p = CreateMaybeMessage<::sglang::SamplingParams>(GetArenaForAllocation());
    _impl_.sampling_params_ = p;
  }
  return _impl_.sampling_params_;
}
inline ::sglang::SamplingParams* GenerateReq::mutable_sampling_params() {
  ::sglang::SamplingParams* _msg = _internal_mutable_sampling_params();
  // @@protoc_insertion_point(field_mutable:sglang.GenerateReq.sampling_params)
  return _msg;
}
inline void GenerateReq::set_allocated_sampling_params(::sglang::SamplingParams* sampling_params) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.sampling_params_;
  }
  if (sampling_params) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(sampling_params);
    if (message_arena != submessage_arena) {
      sampling_params = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sampling_params, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.sampling_params_ = sampling_params;
  // @@protoc_insertion_point(field_set_allocated:sglang.GenerateReq.sampling_params)
}

// uint64 req_id = 4;
inline void GenerateReq::clear_req_id() {
  _impl_.req_id_ = uint64_t{0u};
}
inline uint64_t GenerateReq::_internal_req_id() const {
  return _impl_.req_id_;
}
inline uint64_t GenerateReq::req_id() const {
  // @@protoc_insertion_point(field_get:sglang.GenerateReq.req_id)
  return _internal_req_id();
}
inline void GenerateReq::_internal_set_req_id(uint64_t value) {
  
  _impl_.req_id_ = value;
}
inline void GenerateReq::set_req_id(uint64_t value) {
  _internal_set_req_id(value);
  // @@protoc_insertion_point(field_set:sglang.GenerateReq.req_id)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GenerateResp

// string text = 1;
inline void GenerateResp::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& GenerateResp::text() const {
  // @@protoc_insertion_point(field_get:sglang.GenerateResp.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GenerateResp::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sglang.GenerateResp.text)
}
inline std::string* GenerateResp::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:sglang.GenerateResp.text)
  return _s;
}
inline const std::string& GenerateResp::_internal_text() const {
  return _impl_.text_.Get();
}
inline void GenerateResp::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* GenerateResp::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* GenerateResp::release_text() {
  // @@protoc_insertion_point(field_release:sglang.GenerateResp.text)
  return _impl_.text_.Release();
}
inline void GenerateResp::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sglang.GenerateResp.text)
}

// repeated int32 output_ids = 2;
inline int GenerateResp::_internal_output_ids_size() const {
  return _impl_.output_ids_.size();
}
inline int GenerateResp::output_ids_size() const {
  return _internal_output_ids_size();
}
inline void GenerateResp::clear_output_ids() {
  _impl_.output_ids_.Clear();
}
inline int32_t GenerateResp::_internal_output_ids(int index) const {
  return _impl_.output_ids_.Get(index);
}
inline int32_t GenerateResp::output_ids(int index) const {
  // @@protoc_insertion_point(field_get:sglang.GenerateResp.output_ids)
  return _internal_output_ids(index);
}
inline void GenerateResp::set_output_ids(int index, int32_t value) {
  _impl_.output_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:sglang.GenerateResp.output_ids)
}
inline void GenerateResp::_internal_add_output_ids(int32_t value) {
  _impl_.output_ids_.Add(value);
}
inline void GenerateResp::add_output_ids(int32_t value) {
  _internal_add_output_ids(value);
  // @@protoc_insertion_point(field_add:sglang.GenerateResp.output_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GenerateResp::_internal_output_ids() const {
  return _impl_.output_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GenerateResp::output_ids() const {
  // @@protoc_insertion_point(field_list:sglang.GenerateResp.output_ids)
  return _internal_output_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GenerateResp::_internal_mutable_output_ids() {
  return &_impl_.output_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GenerateResp::mutable_output_ids() {
  // @@protoc_insertion_point(field_mutable_list:sglang.GenerateResp.output_ids)
  return _internal_mutable_output_ids();
}

// map<string, float> meta_info = 3;
inline int GenerateResp::_internal_meta_info_size() const {
  return _impl_.meta_info_.size();
}
inline int GenerateResp::meta_info_size() const {
  return _internal_meta_info_size();
}
inline void GenerateResp::clear_meta_info() {
  _impl_.meta_info_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
GenerateResp::_internal_meta_info() const {
  return _impl_.meta_info_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
GenerateResp::meta_info() const {
  // @@protoc_insertion_point(field_map:sglang.GenerateResp.meta_info)
  return _internal_meta_info();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
GenerateResp::_internal_mutable_meta_info() {
  return _impl_.meta_info_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
GenerateResp::mutable_meta_info() {
  // @@protoc_insertion_point(field_mutable_map:sglang.GenerateResp.meta_info)
  return _internal_mutable_meta_info();
}

// bool finished = 4;
inline void GenerateResp::clear_finished() {
  _impl_.finished_ = false;
}
inline bool GenerateResp::_internal_finished() const {
  return _impl_.finished_;
}
inline bool GenerateResp::finished() const {
  // @@protoc_insertion_point(field_get:sglang.GenerateResp.finished)
  return _internal_finished();
}
inline void GenerateResp::_internal_set_finished(bool value) {
  
  _impl_.finished_ = value;
}
inline void GenerateResp::set_finished(bool value) {
  _internal_set_finished(value);
  // @@protoc_insertion_point(field_set:sglang.GenerateResp.finished)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sglang

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fsglang_2eproto
