// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/sglang.proto

#include "proto/sglang.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sglang {
PROTOBUF_CONSTEXPR SamplingParams::SamplingParams(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.max_new_tokens_)*/0
  , /*decltype(_impl_.stop_token_id_)*/0
  , /*decltype(_impl_.ignore_eos_)*/false
  , /*decltype(_impl_.temperature_)*/0
  , /*decltype(_impl_.top_p_)*/0
  , /*decltype(_impl_.top_k_)*/0
  , /*decltype(_impl_.frequency_penalty_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SamplingParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SamplingParamsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SamplingParamsDefaultTypeInternal() {}
  union {
    SamplingParams _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SamplingParamsDefaultTypeInternal _SamplingParams_default_instance_;
PROTOBUF_CONSTEXPR GenerateReq::GenerateReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.input_ids_)*/{}
  , /*decltype(_impl_._input_ids_cached_byte_size_)*/{0}
  , /*decltype(_impl_.text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sampling_params_)*/nullptr
  , /*decltype(_impl_.req_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GenerateReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateReqDefaultTypeInternal() {}
  union {
    GenerateReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateReqDefaultTypeInternal _GenerateReq_default_instance_;
PROTOBUF_CONSTEXPR GenerateResp_MetaInfoEntry_DoNotUse::GenerateResp_MetaInfoEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct GenerateResp_MetaInfoEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateResp_MetaInfoEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateResp_MetaInfoEntry_DoNotUseDefaultTypeInternal() {}
  union {
    GenerateResp_MetaInfoEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateResp_MetaInfoEntry_DoNotUseDefaultTypeInternal _GenerateResp_MetaInfoEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR GenerateResp::GenerateResp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.output_ids_)*/{}
  , /*decltype(_impl_._output_ids_cached_byte_size_)*/{0}
  , /*decltype(_impl_.meta_info_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.finished_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GenerateRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateRespDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateRespDefaultTypeInternal() {}
  union {
    GenerateResp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateRespDefaultTypeInternal _GenerateResp_default_instance_;
}  // namespace sglang
static ::_pb::Metadata file_level_metadata_proto_2fsglang_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fsglang_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fsglang_2eproto = nullptr;

const uint32_t TableStruct_proto_2fsglang_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sglang::SamplingParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sglang::SamplingParams, _impl_.max_new_tokens_),
  PROTOBUF_FIELD_OFFSET(::sglang::SamplingParams, _impl_.stop_token_id_),
  PROTOBUF_FIELD_OFFSET(::sglang::SamplingParams, _impl_.ignore_eos_),
  PROTOBUF_FIELD_OFFSET(::sglang::SamplingParams, _impl_.temperature_),
  PROTOBUF_FIELD_OFFSET(::sglang::SamplingParams, _impl_.top_p_),
  PROTOBUF_FIELD_OFFSET(::sglang::SamplingParams, _impl_.top_k_),
  PROTOBUF_FIELD_OFFSET(::sglang::SamplingParams, _impl_.frequency_penalty_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateReq, _impl_.text_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateReq, _impl_.input_ids_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateReq, _impl_.sampling_params_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateReq, _impl_.req_id_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp_MetaInfoEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp_MetaInfoEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp_MetaInfoEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp_MetaInfoEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp, _impl_.text_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp, _impl_.output_ids_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp, _impl_.meta_info_),
  PROTOBUF_FIELD_OFFSET(::sglang::GenerateResp, _impl_.finished_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::sglang::SamplingParams)},
  { 13, -1, -1, sizeof(::sglang::GenerateReq)},
  { 23, 31, -1, sizeof(::sglang::GenerateResp_MetaInfoEntry_DoNotUse)},
  { 33, -1, -1, sizeof(::sglang::GenerateResp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sglang::_SamplingParams_default_instance_._instance,
  &::sglang::_GenerateReq_default_instance_._instance,
  &::sglang::_GenerateResp_MetaInfoEntry_DoNotUse_default_instance_._instance,
  &::sglang::_GenerateResp_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fsglang_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022proto/sglang.proto\022\006sglang\"\241\001\n\016Samplin"
  "gParams\022\026\n\016max_new_tokens\030\001 \001(\005\022\025\n\rstop_"
  "token_id\030\002 \001(\005\022\022\n\nignore_eos\030\003 \001(\010\022\023\n\013te"
  "mperature\030\004 \001(\002\022\r\n\005top_p\030\005 \001(\002\022\r\n\005top_k\030"
  "\006 \001(\005\022\031\n\021frequency_penalty\030\007 \001(\002\"o\n\013Gene"
  "rateReq\022\014\n\004text\030\001 \001(\t\022\021\n\tinput_ids\030\002 \003(\005"
  "\022/\n\017sampling_params\030\003 \001(\0132\026.sglang.Sampl"
  "ingParams\022\016\n\006req_id\030\004 \001(\004\"\252\001\n\014GenerateRe"
  "sp\022\014\n\004text\030\001 \001(\t\022\022\n\noutput_ids\030\002 \003(\005\0225\n\t"
  "meta_info\030\003 \003(\0132\".sglang.GenerateResp.Me"
  "taInfoEntry\022\020\n\010finished\030\004 \001(\010\032/\n\rMetaInf"
  "oEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\002:\0028\0012F"
  "\n\rSGLangService\0225\n\010Generate\022\023.sglang.Gen"
  "erateReq\032\024.sglang.GenerateRespb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2fsglang_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fsglang_2eproto = {
    false, false, 558, descriptor_table_protodef_proto_2fsglang_2eproto,
    "proto/sglang.proto",
    &descriptor_table_proto_2fsglang_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_proto_2fsglang_2eproto::offsets,
    file_level_metadata_proto_2fsglang_2eproto, file_level_enum_descriptors_proto_2fsglang_2eproto,
    file_level_service_descriptors_proto_2fsglang_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fsglang_2eproto_getter() {
  return &descriptor_table_proto_2fsglang_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fsglang_2eproto(&descriptor_table_proto_2fsglang_2eproto);
namespace sglang {

// ===================================================================

class SamplingParams::_Internal {
 public:
};

SamplingParams::SamplingParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sglang.SamplingParams)
}
SamplingParams::SamplingParams(const SamplingParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SamplingParams* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.max_new_tokens_){}
    , decltype(_impl_.stop_token_id_){}
    , decltype(_impl_.ignore_eos_){}
    , decltype(_impl_.temperature_){}
    , decltype(_impl_.top_p_){}
    , decltype(_impl_.top_k_){}
    , decltype(_impl_.frequency_penalty_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.max_new_tokens_, &from._impl_.max_new_tokens_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.frequency_penalty_) -
    reinterpret_cast<char*>(&_impl_.max_new_tokens_)) + sizeof(_impl_.frequency_penalty_));
  // @@protoc_insertion_point(copy_constructor:sglang.SamplingParams)
}

inline void SamplingParams::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.max_new_tokens_){0}
    , decltype(_impl_.stop_token_id_){0}
    , decltype(_impl_.ignore_eos_){false}
    , decltype(_impl_.temperature_){0}
    , decltype(_impl_.top_p_){0}
    , decltype(_impl_.top_k_){0}
    , decltype(_impl_.frequency_penalty_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SamplingParams::~SamplingParams() {
  // @@protoc_insertion_point(destructor:sglang.SamplingParams)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SamplingParams::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SamplingParams::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SamplingParams::Clear() {
// @@protoc_insertion_point(message_clear_start:sglang.SamplingParams)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.max_new_tokens_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.frequency_penalty_) -
      reinterpret_cast<char*>(&_impl_.max_new_tokens_)) + sizeof(_impl_.frequency_penalty_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SamplingParams::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 max_new_tokens = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.max_new_tokens_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 stop_token_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.stop_token_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ignore_eos = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.ignore_eos_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float temperature = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.temperature_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float top_p = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.top_p_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 top_k = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.top_k_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float frequency_penalty = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _impl_.frequency_penalty_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SamplingParams::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sglang.SamplingParams)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 max_new_tokens = 1;
  if (this->_internal_max_new_tokens() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_max_new_tokens(), target);
  }

  // int32 stop_token_id = 2;
  if (this->_internal_stop_token_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_stop_token_id(), target);
  }

  // bool ignore_eos = 3;
  if (this->_internal_ignore_eos() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_ignore_eos(), target);
  }

  // float temperature = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = this->_internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_temperature(), target);
  }

  // float top_p = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_top_p = this->_internal_top_p();
  uint32_t raw_top_p;
  memcpy(&raw_top_p, &tmp_top_p, sizeof(tmp_top_p));
  if (raw_top_p != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_top_p(), target);
  }

  // int32 top_k = 6;
  if (this->_internal_top_k() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_top_k(), target);
  }

  // float frequency_penalty = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_frequency_penalty = this->_internal_frequency_penalty();
  uint32_t raw_frequency_penalty;
  memcpy(&raw_frequency_penalty, &tmp_frequency_penalty, sizeof(tmp_frequency_penalty));
  if (raw_frequency_penalty != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_frequency_penalty(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sglang.SamplingParams)
  return target;
}

size_t SamplingParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sglang.SamplingParams)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 max_new_tokens = 1;
  if (this->_internal_max_new_tokens() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_max_new_tokens());
  }

  // int32 stop_token_id = 2;
  if (this->_internal_stop_token_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_stop_token_id());
  }

  // bool ignore_eos = 3;
  if (this->_internal_ignore_eos() != 0) {
    total_size += 1 + 1;
  }

  // float temperature = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = this->_internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    total_size += 1 + 4;
  }

  // float top_p = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_top_p = this->_internal_top_p();
  uint32_t raw_top_p;
  memcpy(&raw_top_p, &tmp_top_p, sizeof(tmp_top_p));
  if (raw_top_p != 0) {
    total_size += 1 + 4;
  }

  // int32 top_k = 6;
  if (this->_internal_top_k() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_top_k());
  }

  // float frequency_penalty = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_frequency_penalty = this->_internal_frequency_penalty();
  uint32_t raw_frequency_penalty;
  memcpy(&raw_frequency_penalty, &tmp_frequency_penalty, sizeof(tmp_frequency_penalty));
  if (raw_frequency_penalty != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SamplingParams::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SamplingParams::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SamplingParams::GetClassData() const { return &_class_data_; }


void SamplingParams::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SamplingParams*>(&to_msg);
  auto& from = static_cast<const SamplingParams&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sglang.SamplingParams)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_max_new_tokens() != 0) {
    _this->_internal_set_max_new_tokens(from._internal_max_new_tokens());
  }
  if (from._internal_stop_token_id() != 0) {
    _this->_internal_set_stop_token_id(from._internal_stop_token_id());
  }
  if (from._internal_ignore_eos() != 0) {
    _this->_internal_set_ignore_eos(from._internal_ignore_eos());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = from._internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    _this->_internal_set_temperature(from._internal_temperature());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_top_p = from._internal_top_p();
  uint32_t raw_top_p;
  memcpy(&raw_top_p, &tmp_top_p, sizeof(tmp_top_p));
  if (raw_top_p != 0) {
    _this->_internal_set_top_p(from._internal_top_p());
  }
  if (from._internal_top_k() != 0) {
    _this->_internal_set_top_k(from._internal_top_k());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_frequency_penalty = from._internal_frequency_penalty();
  uint32_t raw_frequency_penalty;
  memcpy(&raw_frequency_penalty, &tmp_frequency_penalty, sizeof(tmp_frequency_penalty));
  if (raw_frequency_penalty != 0) {
    _this->_internal_set_frequency_penalty(from._internal_frequency_penalty());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SamplingParams::CopyFrom(const SamplingParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sglang.SamplingParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SamplingParams::IsInitialized() const {
  return true;
}

void SamplingParams::InternalSwap(SamplingParams* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SamplingParams, _impl_.frequency_penalty_)
      + sizeof(SamplingParams::_impl_.frequency_penalty_)
      - PROTOBUF_FIELD_OFFSET(SamplingParams, _impl_.max_new_tokens_)>(
          reinterpret_cast<char*>(&_impl_.max_new_tokens_),
          reinterpret_cast<char*>(&other->_impl_.max_new_tokens_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SamplingParams::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fsglang_2eproto_getter, &descriptor_table_proto_2fsglang_2eproto_once,
      file_level_metadata_proto_2fsglang_2eproto[0]);
}

// ===================================================================

class GenerateReq::_Internal {
 public:
  static const ::sglang::SamplingParams& sampling_params(const GenerateReq* msg);
};

const ::sglang::SamplingParams&
GenerateReq::_Internal::sampling_params(const GenerateReq* msg) {
  return *msg->_impl_.sampling_params_;
}
GenerateReq::GenerateReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sglang.GenerateReq)
}
GenerateReq::GenerateReq(const GenerateReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GenerateReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.input_ids_){from._impl_.input_ids_}
    , /*decltype(_impl_._input_ids_cached_byte_size_)*/{0}
    , decltype(_impl_.text_){}
    , decltype(_impl_.sampling_params_){nullptr}
    , decltype(_impl_.req_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text().empty()) {
    _this->_impl_.text_.Set(from._internal_text(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_sampling_params()) {
    _this->_impl_.sampling_params_ = new ::sglang::SamplingParams(*from._impl_.sampling_params_);
  }
  _this->_impl_.req_id_ = from._impl_.req_id_;
  // @@protoc_insertion_point(copy_constructor:sglang.GenerateReq)
}

inline void GenerateReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.input_ids_){arena}
    , /*decltype(_impl_._input_ids_cached_byte_size_)*/{0}
    , decltype(_impl_.text_){}
    , decltype(_impl_.sampling_params_){nullptr}
    , decltype(_impl_.req_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GenerateReq::~GenerateReq() {
  // @@protoc_insertion_point(destructor:sglang.GenerateReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GenerateReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.input_ids_.~RepeatedField();
  _impl_.text_.Destroy();
  if (this != internal_default_instance()) delete _impl_.sampling_params_;
}

void GenerateReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GenerateReq::Clear() {
// @@protoc_insertion_point(message_clear_start:sglang.GenerateReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.input_ids_.Clear();
  _impl_.text_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.sampling_params_ != nullptr) {
    delete _impl_.sampling_params_;
  }
  _impl_.sampling_params_ = nullptr;
  _impl_.req_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GenerateReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string text = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sglang.GenerateReq.text"));
        } else
          goto handle_unusual;
        continue;
      // repeated int32 input_ids = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_input_ids(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_input_ids(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sglang.SamplingParams sampling_params = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_sampling_params(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 req_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.req_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GenerateReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sglang.GenerateReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string text = 1;
  if (!this->_internal_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sglang.GenerateReq.text");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_text(), target);
  }

  // repeated int32 input_ids = 2;
  {
    int byte_size = _impl_._input_ids_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_input_ids(), byte_size, target);
    }
  }

  // .sglang.SamplingParams sampling_params = 3;
  if (this->_internal_has_sampling_params()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::sampling_params(this),
        _Internal::sampling_params(this).GetCachedSize(), target, stream);
  }

  // uint64 req_id = 4;
  if (this->_internal_req_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_req_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sglang.GenerateReq)
  return target;
}

size_t GenerateReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sglang.GenerateReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 input_ids = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.input_ids_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._input_ids_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string text = 1;
  if (!this->_internal_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  // .sglang.SamplingParams sampling_params = 3;
  if (this->_internal_has_sampling_params()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.sampling_params_);
  }

  // uint64 req_id = 4;
  if (this->_internal_req_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_req_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GenerateReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GenerateReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GenerateReq::GetClassData() const { return &_class_data_; }


void GenerateReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GenerateReq*>(&to_msg);
  auto& from = static_cast<const GenerateReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sglang.GenerateReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.input_ids_.MergeFrom(from._impl_.input_ids_);
  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  if (from._internal_has_sampling_params()) {
    _this->_internal_mutable_sampling_params()->::sglang::SamplingParams::MergeFrom(
        from._internal_sampling_params());
  }
  if (from._internal_req_id() != 0) {
    _this->_internal_set_req_id(from._internal_req_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GenerateReq::CopyFrom(const GenerateReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sglang.GenerateReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GenerateReq::IsInitialized() const {
  return true;
}

void GenerateReq::InternalSwap(GenerateReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.input_ids_.InternalSwap(&other->_impl_.input_ids_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_, lhs_arena,
      &other->_impl_.text_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GenerateReq, _impl_.req_id_)
      + sizeof(GenerateReq::_impl_.req_id_)
      - PROTOBUF_FIELD_OFFSET(GenerateReq, _impl_.sampling_params_)>(
          reinterpret_cast<char*>(&_impl_.sampling_params_),
          reinterpret_cast<char*>(&other->_impl_.sampling_params_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GenerateReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fsglang_2eproto_getter, &descriptor_table_proto_2fsglang_2eproto_once,
      file_level_metadata_proto_2fsglang_2eproto[1]);
}

// ===================================================================

GenerateResp_MetaInfoEntry_DoNotUse::GenerateResp_MetaInfoEntry_DoNotUse() {}
GenerateResp_MetaInfoEntry_DoNotUse::GenerateResp_MetaInfoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void GenerateResp_MetaInfoEntry_DoNotUse::MergeFrom(const GenerateResp_MetaInfoEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata GenerateResp_MetaInfoEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fsglang_2eproto_getter, &descriptor_table_proto_2fsglang_2eproto_once,
      file_level_metadata_proto_2fsglang_2eproto[2]);
}

// ===================================================================

class GenerateResp::_Internal {
 public:
};

GenerateResp::GenerateResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &GenerateResp::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:sglang.GenerateResp)
}
GenerateResp::GenerateResp(const GenerateResp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GenerateResp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.output_ids_){from._impl_.output_ids_}
    , /*decltype(_impl_._output_ids_cached_byte_size_)*/{0}
    , /*decltype(_impl_.meta_info_)*/{}
    , decltype(_impl_.text_){}
    , decltype(_impl_.finished_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.meta_info_.MergeFrom(from._impl_.meta_info_);
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text().empty()) {
    _this->_impl_.text_.Set(from._internal_text(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.finished_ = from._impl_.finished_;
  // @@protoc_insertion_point(copy_constructor:sglang.GenerateResp)
}

inline void GenerateResp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.output_ids_){arena}
    , /*decltype(_impl_._output_ids_cached_byte_size_)*/{0}
    , /*decltype(_impl_.meta_info_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.text_){}
    , decltype(_impl_.finished_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GenerateResp::~GenerateResp() {
  // @@protoc_insertion_point(destructor:sglang.GenerateResp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void GenerateResp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.output_ids_.~RepeatedField();
  _impl_.meta_info_.Destruct();
  _impl_.meta_info_.~MapField();
  _impl_.text_.Destroy();
}

void GenerateResp::ArenaDtor(void* object) {
  GenerateResp* _this = reinterpret_cast< GenerateResp* >(object);
  _this->_impl_.meta_info_.Destruct();
}
void GenerateResp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GenerateResp::Clear() {
// @@protoc_insertion_point(message_clear_start:sglang.GenerateResp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.output_ids_.Clear();
  _impl_.meta_info_.Clear();
  _impl_.text_.ClearToEmpty();
  _impl_.finished_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GenerateResp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string text = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sglang.GenerateResp.text"));
        } else
          goto handle_unusual;
        continue;
      // repeated int32 output_ids = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_output_ids(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_output_ids(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, float> meta_info = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.meta_info_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // bool finished = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.finished_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GenerateResp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sglang.GenerateResp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string text = 1;
  if (!this->_internal_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sglang.GenerateResp.text");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_text(), target);
  }

  // repeated int32 output_ids = 2;
  {
    int byte_size = _impl_._output_ids_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_output_ids(), byte_size, target);
    }
  }

  // map<string, float> meta_info = 3;
  if (!this->_internal_meta_info().empty()) {
    using MapType = ::_pb::Map<std::string, float>;
    using WireHelper = GenerateResp_MetaInfoEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_meta_info();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "sglang.GenerateResp.MetaInfoEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // bool finished = 4;
  if (this->_internal_finished() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_finished(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sglang.GenerateResp)
  return target;
}

size_t GenerateResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sglang.GenerateResp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 output_ids = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.output_ids_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._output_ids_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // map<string, float> meta_info = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_meta_info_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, float >::const_iterator
      it = this->_internal_meta_info().begin();
      it != this->_internal_meta_info().end(); ++it) {
    total_size += GenerateResp_MetaInfoEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string text = 1;
  if (!this->_internal_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  // bool finished = 4;
  if (this->_internal_finished() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GenerateResp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GenerateResp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GenerateResp::GetClassData() const { return &_class_data_; }


void GenerateResp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GenerateResp*>(&to_msg);
  auto& from = static_cast<const GenerateResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sglang.GenerateResp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.output_ids_.MergeFrom(from._impl_.output_ids_);
  _this->_impl_.meta_info_.MergeFrom(from._impl_.meta_info_);
  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  if (from._internal_finished() != 0) {
    _this->_internal_set_finished(from._internal_finished());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GenerateResp::CopyFrom(const GenerateResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sglang.GenerateResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GenerateResp::IsInitialized() const {
  return true;
}

void GenerateResp::InternalSwap(GenerateResp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.output_ids_.InternalSwap(&other->_impl_.output_ids_);
  _impl_.meta_info_.InternalSwap(&other->_impl_.meta_info_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_, lhs_arena,
      &other->_impl_.text_, rhs_arena
  );
  swap(_impl_.finished_, other->_impl_.finished_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GenerateResp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fsglang_2eproto_getter, &descriptor_table_proto_2fsglang_2eproto_once,
      file_level_metadata_proto_2fsglang_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sglang
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sglang::SamplingParams*
Arena::CreateMaybeMessage< ::sglang::SamplingParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sglang::SamplingParams >(arena);
}
template<> PROTOBUF_NOINLINE ::sglang::GenerateReq*
Arena::CreateMaybeMessage< ::sglang::GenerateReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sglang::GenerateReq >(arena);
}
template<> PROTOBUF_NOINLINE ::sglang::GenerateResp_MetaInfoEntry_DoNotUse*
Arena::CreateMaybeMessage< ::sglang::GenerateResp_MetaInfoEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sglang::GenerateResp_MetaInfoEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::sglang::GenerateResp*
Arena::CreateMaybeMessage< ::sglang::GenerateResp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sglang::GenerateResp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
